export const labels = {
  common: {
    edit: "Editar",
    delete: "Eliminar",
    cancel: "Cancelar",
    save: "Guardar",
    saveBtn: "Crear",
    saving: "Guardando…",
    deleting: "Eliminando…",
    login: "Iniciar sesión",
    signup: "Registrarse",
    backHome: "← Volver al inicio",
    loading: "Cargando...",
    add: "Agregar",
    element: "elemento",
    errorUnknown: "Error desconocido",
    errorDelete: "No se pudo eliminar. Inténtalo de nuevo.",
    deleteTitle: (label: string) => `Eliminar ${label}`,
    deleteConfirm: (label: string) => `¿Eliminar ${label}? Esta acción no se puede deshacer.`,
    editSingular: (s: string) => `Editar ${s}`,
    newSingular: (s: string) => `Nuevo ${s}`,
  },

  field: {
    name: "Nombre",
    description: "Descripción",
    amount: "Monto",
    currency: "Moneda",
    category: "Categoría",
    type: "Tipo",
    color: "Color",
    notes: "Notas",
    method: "Método",
    card: "Tarjeta",
    date: "Fecha",
    status: "Estado",
    title: "Título",
    content: "Contenido",
    pinned: "Fijada",
    quantity: "Cantidad",
    item: "Artículo",
    location: "Ubicación",
    start: "Inicio",
    end: "Fin",
    allDay: "Día completo",
    sections: "Secciones",
    noCategory: "Sin categoría",
    noCard: "Sin tarjeta",
    totalAmount: "Monto total",
    monthlyFee: "Cuota mensual",
    totalMonths: "Total de meses",
    dueDate: "Fecha de vencimiento",
    priority: "Prioridad",
    maxLimit: "Límite máximo",
    cutoffDay: "Día de corte",
    paymentDueDay: "Fecha límite de pago",
    iconEmoji: "Ícono (emoji)",
    paymentDate: "Fecha de pago",
    partialPayment: "Pago parcial",
    iconPlaceholder: "💳",
  },

  table: {
    actions: "Acciones",
    date: "Fecha",
    description: "Descripción",
    amount: "Monto",
    currency: "Moneda",
    method: "Método",
    category: "Categoría",
    type: "Tipo",
    total: "Total",
    fee: "Cuota",
    progress: "Progreso",
    card: "Tarjeta",
    debt: "Deuda",
    status: "Estado",
    month: "Mes",
    item: "Artículo",
    qty: "Cant.",
    notes: "Notas",
    name: "Nombre",
    limit: "Límite",
    cutoff: "Corte",
    dueDay: "Límite de pago",
    icon: "Icono",
    color: "Color",
    sections: "Secciones",
  },

  empty: {
    data: "Sin datos",
    transactions: "Sin transacciones",
    installments: "Sin plazos",
    cashback: "Sin cashback",
    pantry: "Sin productos en la despensa",
    history: "Sin datos históricos",
    activeInstallments: "No hay plazos activos",
    creditCards: "No hay tarjetas de crédito registradas",
    cards: "Sin tarjetas",
    recurring: "Sin pagos recurrentes",
    recurringMonthly: "No hay pagos recurrentes registrados.",
    tasks: "Sin tareas",
    notes: "Sin notas",
    events: "Sin eventos",
    paymentMethods: "Sin métodos de pago",
    categories: "Sin categorías",
    shoppingActive: "Agrega productos desde la despensa o escribe el nombre",
    shoppingHistory: "Sin compras completadas aún",
    noTitle: "Sin título",
  },

  badge: {
    income: "Ingreso",
    expense: "Gasto",
    incomeOption: "📥 Ingreso",
    expenseOption: "💸 Gasto",
    paid: "Pagado",
    paidF: "Pagada",
    paidLate: "Pagada tarde",
    pending: "Pendiente",
    overdue: "Vencido",
    received: "Recibido",
    credit: "Crédito",
    debit: "Débito",
    voucher: "Vales",
    voucherFull: "Vales de despensa",
    global: "Global",
    personal: "Personal",
    card: "Tarjeta",
    low: "🟢 Baja",
    medium: "🟡 Media",
    high: "🔴 Alta",
    lowOption: "🟢 1 - Baja",
    mediumOption: "🟡 2 - Media",
    highOption: "🔴 3 - Alta",
    pendingEvent: "🟡 Pendiente",
    confirmed: "🔵 Confirmado",
    completed: "🟢 Completado",
    cancelled: "🔴 Cancelado",
  },

  stat: {
    incomes: "Ingresos",
    expenses: "Gastos",
    balance: "Balance",
    movements: "Movimientos",
    total: "Total",
    received: "Recibidos",
    paid: "Pagados",
    pending: "Pendiente",
    limit: "Límite",
    calculatedDebt: "Deuda calculada",
    available: "Disponible",
    cutoffPayment: "Corte / Pago",
    paymentDue: "Límite de pago:",
    purchases: "Compras",
    installmentsThisMonth: "Plazos (este mes)",
    recurringPayments: "Pagos recurrentes",
    cashback: "Cashback",
    monthDebt: "Adeudo del mes",
    futureInstallments: "Plazos futuros",
    totalCommitted: "Total comprometido",
    activeInstallments: "Plazos activos",
    remainingToPay: "Restante por pagar",
    totalFees: "Total de cuotas",
    remaining: "Restante",
    fee: "Cuota",
  },

  tabs: {
    summary: "Resumen",
    history: "Historial",
    adminCards: "Administrar tarjetas",
    adminInstallments: "Administrar plazos",
    adminRecurring: "Administrar pagos recurrentes",
    currentList: "Listas de compras",
    ariaInstallments: "Secciones de plazos",
  },

  nav: {
    dashboard: "Dashboard",
    transactions: "Transacciones",
    cards: "Tarjetas",
    installments: "Plazos",
    recurringPayments: "Pagos recurrentes",
    cashback: "Cashback",
    paymentMethods: "Métodos de pago",
    shopping: "Compras",
    tasks: "Tareas",
    notes: "Notas",
    events: "Eventos",
    pantry: "Despensa",
    categories: "Categorías",
    groupFinance: "Finanzas",
    groupOrganization: "Organización",
    groupGeneral: "General",
    myAccount: "Mi cuenta",
    ariaMain: "Navegación principal",
    ariaGithub: "GitHub",
    openMenu: "Abrir menú",
  },

  theme: {
    label: "Tema",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
  },

  page: {
    home: "Inicio",
    dashboard: "Dashboard",
    transactions: "Transacciones",
    cards: "Tarjetas",
    installments: "Plazos / Cuotas",
    recurringPayments: "Pagos Recurrentes",
    cashback: "Cashback",
    shopping: "Lista de compras",
    pantry: "Despensa",
    tasks: "Tareas",
    notes: "Notas",
    events: "Eventos",
    paymentMethods: "Métodos de pago",
    categories: "Categorías",
  },

  cta: {
    newTransaction: "Nueva transacción",
    newCard: "Nueva tarjeta",
    newInstallment: "Nuevo plazo",
    newCashback: "Nuevo cashback",
    newRecurring: "Nuevo pago recurrente",
    newProduct: "Nuevo producto",
    newTask: "Nueva tarea",
    newNote: "Nueva nota",
    newEvent: "Nuevo evento",
    newPaymentMethod: "Nuevo método",
    newCategory: "Nueva categoría",
    payCard: "Pagar",
    payAll: "Pagar todo",
    markReceived: "Marcar como recibido",
    markPaid: "Marcar como pagado",
    addToMonth: "Agregar al mes",
    backToPending: "Volver a pendiente",
    removeFromMonth: "Eliminar del mes",
  },

  singular: {
    transaction: "transacción",
    card: "tarjeta",
    installment: "plazo",
    recurringPayment: "pago recurrente",
    cashback: "cashback",
    product: "producto",
    task: "tarea",
    note: "nota",
    event: "evento",
    paymentMethod: "método de pago",
    category: "categoría",
  },

  filter: {
    all: "Todas",
    allCategories: "Todas las categorías",
    allCards: "Todas las tarjetas",
    allPaymentMethods: "Todos los métodos",
    allStatus: "Todos",
    allMonths: "Último año",
    allSections: "Todas las secciones",
    searchDesc: "Buscar por descripción...",
    searchPantry: "Buscar por artículo o nota...",
    labelType: "Tipo",
    labelCategory: "Categoría",
    labelPaymentMethod: "Método de pago",
    labelCard: "Tarjeta",
    labelStatus: "Estado",
    labelMonth: "Mes",
    labelFilter: "Filtrar",
    selectFallback: "Seleccionar...",
    multiSelectFallback: "Seleccionar secciones...",
    btnClear: "Limpiar búsqueda",
    income: "Ingresos",
    expense: "Gastos",
    activeOnly: "Solo activos",
    pendingTasks: "Pendientes",
    doneTasks: "Completadas",
  },

  currency: {
    options: [
      { value: "EUR", label: "EUR €" },
      { value: "MXN", label: "MXN $" },
      { value: "USD", label: "USD $" },
    ],
  },

  shopping: {
    fromPantry: "Desde la despensa",
    addAnother: "Agregar otro",
    searchPlaceholder: "Escribe el nombre del producto...",
    others: "Otros",
    toBuy: (n: number) => `Por comprar (${n})`,
    bought: (n: number) => `Comprados (${n})`,
    ariaSections: "Secciones de compras",
    newList: "Nueva lista",
    finalizeList: "Finalizar lista",
    deleteList: "Eliminar lista",
    confirmDeleteList: "¿Eliminar esta lista y sus artículos?",
    listNamePlaceholder: "Nombre de la lista",
    addTo: "Agregar a",
    itemCount: (n: number) => `${n} ${n === 1 ? "artículo" : "artículos"}`,
    emptyLists: "Crea una lista de compras para empezar",
    completedOn: "Completada el",
  },

  cards: {
    payCardTitle: "Pagar tarjeta",
    or: "o",
    zeroPlaceholder: "0.00",
    remainingNote: (amount: string) => `Restante: ${amount} — se agregará como gasto al mes siguiente`,
    dueIn: (days: number, day: number) => `En ${days} días (día ${day})`,
    historyTitle: "Historial de tarjetas",
    allCardsRegistered: "Todas tus tarjetas registradas",
    ariaTabs: "Secciones de tarjetas",
  },

  recurring: {
    historyTitle: "Historial de pagos recurrentes",
    allRegistered: "Todos tus pagos recurrentes registrados",
    noCategory: "Sin categoría",
    ariaTabs: "Secciones de pagos recurrentes",
  },

  dashboard: {
    statIncomes: "Ingresos",
    statExpenses: "Gastos",
    statBalance: "Balance",
    statCreditCards: "Tarjetas de crédito",
    statInstallments: "Plazos",
    statPendingTasks: "Tareas pendientes",
    statUpcomingEvents: "Próximos eventos",
    statActiveShopping: "Compras activas",
    statRecurring: "Pagos recurrentes",
    statRecurringExpenses: "Gastos recurrentes",
    cardDebtsTitle: "Deudas de tarjetas de crédito del mes",
    recurringIncomesTitle: "💵 Ingresos recurrentes",
    recurringExpensesTitle: "💰 Gastos recurrentes",
    monthTransactionsTitle: "Transacciones del mes",
    noDescription: "Sin descripción",
    overdueCount: (n: number) => `${n} vencidas`,
    dueInDays: (n: number) => `${n} días`,
  },

  sections: {
    pantry: "Despensa",
    tasks: "Tareas",
    transactions: "Transacciones",
    installments: "Plazos",
    events: "Eventos",
    recurringPayments: "Pagos recurrentes",
  },

  landing: {
    heroTitle: "Controla tus",
    heroTitleAccent: "finanzas personales",
    heroDescription: "Open PRP es tu centro de gestión financiera personal. Transacciones, tarjetas, plazos, suscripciones, despensa y más, todo en un solo lugar.",
    ctaStart: "Comenzar gratis",
    ctaMore: "Ver más",
    featuresTitle: "Todo lo que necesitas",
    featuresTagline: "Gestiona cada aspecto de tus finanzas desde un solo panel.",
    features: [
      { title: "Transacciones", description: "Registra ingresos y gastos con categorías personalizadas." },
      { title: "Tarjetas", description: "Controla tus plásticos, fechas de corte y pagos mensuales." },
      { title: "Plazos", description: "Divide compras en cuotas y da seguimiento a cada una." },
      { title: "Pagos recurrentes", description: "Suscripciones y servicios con registro mensual automático." },
      { title: "Despensa", description: "Inventario de productos, fechas de vencimiento y compras." },
      { title: "Compras", description: "Lista de compras con historial y categorías." },
    ],
    navFeatures: "Características",
    navAbout: "Sobre Mí",
    ariaMenu: "Menú",
    login: "Login",
    developedWith: "Desarrollado con",
  },

  select: {
    ariaOptions: "Opciones",
    ariaSections: "Secciones",
    countSections: (n: number) => `${n} secciones`,
    ariaCurrency: "Moneda",
  },

  error: {
    message: (message: string) => `Error: ${message}`,
  },
} as const;

export type Labels = typeof labels;
