packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.8'
  - '@astrojs/netlify@8.2.4'
  - '@clerk/astro@4.0.19'
  - '@clerk/backend@3.16.12'
  - '@clerk/localizations@4.15.7'
  - '@clerk/shared@4.30.1'
  - astro@7.2.6
