ALTER TABLE installments ADD COLUMN currency TEXT NOT NULL DEFAULT 'MXN';
ALTER TABLE recurring_payments ADD COLUMN currency TEXT NOT NULL DEFAULT 'MXN';
ALTER TABLE cashback ADD COLUMN currency TEXT NOT NULL DEFAULT 'MXN';
